<?
//ru
$ru = array();
$ru["top-header"] = "Анна Муляр";
$ru["call-to-action"] = "Свяжитесь со мной";
$ru["native"] = "Носитель русского языка. Родилась и выросла в Санкт-Петербурге в семье библиотекаря";
$ru["education"] = "Высшее филологическое образование, профессиональное владение русским языком";
$ru["expeirence"] = "Опыт преподавания русского языка - 2 года. Работаю как с детьми, так и со взрослыми; как в группе, так и индивидуально";
$ru["journalism"] = "Опыт в качестве журналиста различных СМИ на русском языке - 4 года. Работа в ведущих журналах и информационных агентствах России, в том числе РИА-Новости и Cosmopolitan Russia. В 2012 году получила премию в области студенческой журналистики 'Невское перо'.";
$ru["literature"] = "Имею награды и публикации в области писательского мастерства";
$ru["english"] = "Уровень английского - Upper-Intermidiate";
$ru["diction"] = "Профессионально поставленная дикция";
$ru["mindset"] = "Знания менталитета различных стран и народов, успешный опыт работы со студентами из разных стран; среди них - Китай, Индия, Колумбия, Бразилия";
$ru["group"] = "В группе";
$ru["prices"] = "Услуги и цены";
$ru["only"] = "Индивидуально";
$ru["children"] = "Занятия с детьми";
$ru["adults"] = "Занятия со взрослыми";
$ru["trki"] = "Подготовка к ТРКИ";
$ru["name"] = "Как Вас зовут?";
$ru["age"] = "Сколько Вам лет?";
$ru["tel"] = "Какой Ваш контактный телефон?";
$ru["email"] = "Какой Ваш контактный e-mail?";
$ru["goal"] = "Для чего Вы изучаете русский язык?";
$ru["me"] = "Для себя";
$ru["job"] = "Для карьеры";
$ru["study"] = "Для учёбы";
$ru["travel"] = "Для путешествий";
$ru["exam"] = "Для сдачи ТРКИ";
$ru["lover"] = "Любимый мужчина (женщина) из русскоязычной страны";
$ru["other"] = "Другое";
$ru["family"] = "В семье";
$ru["no"] = "Пока не учил(а) русский язык";
$ru["russia"] = "Жил(а) / живу в русскоязычной стране";
$ru["uni"] = "В университете";
$ru["school"] = "В школе";
$ru["courses"] = "На курсах";
$ru["myself"] = "Самостоятельно";
$ru["privTeach"] = "С репетитором";
$ru["nothing"] = "Я пока не знаю русского";
$ru["writing"] = "Письмо";
$ru["pronunciation"] = "Произношение";
$ru["speaking"] = "Говорение";
$ru["reading"] = "Чтение";
$ru["listening"] = "Аудирование";
$ru["culture"] = "Российская культура и жизнь в России";
$ru["grammar"] = "Грамматика";
$ru["problems"] = "Какая часть русского языка вызывает у Вас наибольшие проблемы?";
$ru["send-btn"] = "Отправить";
$ru["study-form"] = "Какая форма занятий предпочтительнее для Вас?";
$ru["prev"] = "Как Вы изучали русский язык ранее?";



//zh
$zh = array();
$zh["top-header"] = "Ni hao";
$zh["call-to-action"] = "Wo shi e guo ren";
$zh["native"] = "E guo ren";
$zh["education"] = "E guo ren";
$zh["expeirence"] = "E guo ren";
$zh["journalism"] = "E guo ren";
$zh["literature"] = "E guo ren";
$zh["english"] = "E guo ren";
$zh["diction"] = "E guo ren";
$zh["mindset"] = "E guo ren";
$zh["group"] = "lylyulyhulhulyhu.";
$zh["prices"] = "lylyulyhulhulyhu.";
$zh["only"] = "lylyulyhulhulyhu.";
$zh["children"] = "lylyulyhulhulyhu.";
$zh["adults"] = "lylyulyhulhulyhu.";
$zh["trki"] = "lylyulyhulhulyhu.";
$zh["name"] = "lylyulyhulhulyhu.";
$zh["age"] = "lylyulyhulhulyhu.";
$zh["tel"] = "lylyulyhulhulyhu.";
$zh["email"] = "lylyulyhulhulyhu.";
$zh["goal"] = "lylyulyhulhulyhu.";
$zh["me"] = "lylyulyhulhulyhu.";
$zh["job"] = "lylyulyhulhulyhu.";
$zh["study"] = "lylyulyhulhulyhu.";
$zh["travel"] = "lylyulyhulhulyhu.";
$zh["exam"] = "lylyulyhulhulyhu.";
$zh["lover"] = "lylyulyhulhulyhu.";
$zh["other"] = "lylyulyhulhulyhu.";
$zh["no"] = "lylyulyhulhulyhu.";
$zh["myself"] = "lylyulyhulhulyhu.";
$zh["school"] = "lylyulyhulhulyhu.";
$zh["uni"] = "lylyulyhulhulyhu.";
$zh["courses"] = "lylyulyhulhulyhu.";
$zh["privTeach"] = "lylyulyhulhulyhu.";
$zh["family"] = "lylyulyhulhulyhu.";
$zh["russia"] = "lylyulyhulhulyhu.";
$zh["nothing"] = "thm;ltdijo;igno;mn";
$zh["writing"] = "thm;ltdijo;igno;mn";
$zh["pronunciation"] = "thm;ltdijo;igno;mn";
$zh["speaking"] = "thm;ltdijo;igno;mn";
$zh["reading"] = "thm;ltdijo;igno;mn";
$zh["listening"] = "thm;ltdijo;igno;mn";
$zh["culture"] = "thm;ltdijo;igno;mn";
$zh["grammar"] = "thm;ltdijo;igno;mn";
$zh["problems"] = "lylyulyhulhulyhu.";
$zh["send-btn"] = "lylyulyhulhulyhu.";
$zh["study-form"] = "lylyulyhulhulyhu.";
$zh["prev"] = "lylyulyhulhulyhu.";


    
//en
$en = array();
$en["top-header"] = "Anja Muljar";
$en["call-to-action"] = "Send to me";
$en["native"] = "Native Russian. I was born and raised in St-Petersburg, my mother works at a library";
$en["education"] = "Higher filological education, professional knowledges of Russian language";
$en["expeirence"] = "2 years expeirence of Russian language teaching. Working expeirence with children and adults, with group and face-by-face";
$en["journalism"] = "4 years expeirence as a journalist in Russian language Mass Media. Working expeirence in the major Russian magazines and news agencies, including RIA-News and Cosmopolitan Russia. I have the 'Neva pen' ('Невское перо') a reward in student journalism field";
$en["literature"] = "Have some literature rewards and publications";
$en["english"] = "Level of my English language is Upper-Intermidiate";
$en["diction"] = "Professional diction";
$en["mindset"] = "Knowledges od the mentalities of different countries and nationalities, successful expeirence off working with students from different countries, including China, India, Colombia, Brazil";
$en["group"] = "In the group";
$en["prices"] = "Services and prices";
$en["only"] = "Personally";
$en["children"] = "Classes with children";
$en["adults"] = "Classes with adults";
$en["trki"] = "ТРКИ preparation";
$en["name"] = "What is your name?";
$en["age"] = "How old are you?";
$en["tel"] = "What is your contact phone?";
$en["email"] = "What is your contact e-mail?";
$en["goal"] = "What is the goal of your Russian studies?";
$en["me"] = "For myself";
$en["job"] = "For my career";
$en["study"] = "For my studies";
$en["travel"] = "For my travelling";
$en["exam"] = "For my ТРКИ preparation";
$en["lover"] = "My lover is from Russian-speaking country";
$en["other"] = "Other";
$en["problems"] = "In the group";
$en["no"] = "In the group";
$en["prev"] = "How did you learn Russian before?";
$en["no"] = "I didn't";
$en["myself"] = "By myself";
$en["school"] = "In school";
$en["uni"] = "In the University";
$en["privTeach"] = "With private teacher";
$en["courses"] = "In the courses";
$en["russia"] = "Living in Russian-speaking country";
$en["family"] = "In my family";
$en["nothing"] = "I don't know Russian yet";
$en["writing"] = "Writing";
$en["pronunciation"] = "Pronunciation";
$en["speaking"] = "Speaking";
$en["reading"] = "Reading";
$en["listening"] = "Listening";
$en["culture"] = "Russian culture and living in Russia";
$en["grammar"] = "Grammar";
$en["problems"] = "What is the most problem point of Russian language for you?";
$en["send-btn"] = "Send";
$en["study-form"] = "What learning form do you prefer?";
$en["prev"] = "What was your previous expeirence of Russian learning?";


//data
$data = array(
    'ru' => $ru,
    'en' => $en,
    'zh' => $zh,
);
?>